notifications:
  email:
      - mrlee_23@naver.com
env:
  global:
      - GH_TOKEN=$G
      - PUBLISHED_DIR=".published"
language: node_js
node_js:
  - "8"
before_script:
  - git config --global user.email "mrlee_23@naver.com"
  - git config --global user.name "mrlee23"
  - npm run doc
  - bash ./build.sh
  - git checkout master
